### ISSUE TITLE
tree not listed as a dependency in the README

### ISSUE THREAD

**Issue by bjjblackbelt** [memoryInject/fzfcache.vim#1]
When running Fzfcache after install, the output from Asyncrun said: 

`/home/x/.local/share/nvim/site/pack/paqs/start/fzfcache.vim/plugin/fzfcache.sh: line 1: tree: command not found`

Consider adding tree as a dependency to the README and also generating an error message if it is not detected. Initially Fzfcache was failing silently. It was only when I happened to have the quickfix window open that I noticed the failure.

**Comment by memoryInject** [comment]
Thank you for pointing this out, I already fix this issue with the latest commit.
If this one is ok, I will close this issue.

**Comment by bjjblackbelt** [comment]
Sounds good. You might also consider using find instead as it is a more ubiquitous Linux utility. Given that you are running asynchronously anyway, any performance difference should not ultimately matter. Or possibly just using find as a fallback if tree is not found.

**Comment by memoryInject** [comment]
You are right about that, I was thinking exactly like that to use find as a fallback option while fixing this issue yesterday.

**Comment by memoryInject** [comment]
I opened a new issue for it #2
